### ISSUE TITLE
"fields" list SELECT * query not recorded in .json file

### ISSUE THREAD

**Issue by mtakahar** [yugabyte/taqo#51]
The field list is empty for this query: `select * from t100000w8k`.

```
"queries": [{"tag": "scans-row-width-variations", "query": "select * from t100000w8k", "query_hash": "fa1756a8ba17a7977dc1c59cbb4ebd29", "tables": [{"alias": "t100000w8k", "name": "t100000w8k", "fields": [], "rows": 100000.0, "size": 0}], 
```

test case: 
[taqo-missing-fields.tar.gz](https://github.com/yugabyte/taqo/files/13227392/taqo-missing-fields.tar.gz)

**Comment by qvad** [comment]
Might be fixed in this [commit](https://github.com/yugabyte/taqo/commit/063e0520c1c4d1dbf211cfa9f3b2b4b0a7a6e097)

**Comment by mtakahar** [comment]
It works with the commit.
